### PR TITLE
Fix one piece mapping

### PR DESCRIPTION
**Pull request by Guslletas**
| AniDB | TVDB/TMDB/IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/69 | https://thetvdb.com/index.php?tab=series&id=81797  | See below |

So one piece can't be mapped using only absolute numbers because anidb episode 590 is mapped to an special(aka season 0 ep 39) so all episodes starting from 591 should have an offset of -1. I've set the whole series offset to -1 and manually mapped the first 589 eps that have no offset.

### CODE REVIEW

**Comment by BrutuZ** [comment]
I haven't looked at this closely yet, but from a quick glance I'm not sure if there's precedent for setting both absolute defaulttvdbseason and episodeoffset.
My fear is the offset affecting the absolute mapping when it shouldn't.

**Comment by Guslletas** [comment]
There are precedents, take a look at Fairy Tail(anidbids 9980 and 13295).

**Comment by BrutuZ** [comment]
Seems this mapping isn't really necessary. The offending episode is properly mapped on TVDB's Absolute order, that the entry already uses
image

**Comment by Guslletas** [comment]
My bad, I thought anime-lists was supposed to match tvdb's aired order and not absolute order

**Comment by BrutuZ** [comment]
Aired order is the most commonly used because most entries are seasonals or one-shots, but it can use absolute ordering as well, especially useful for those long-lasting projects.
That's what the "a" in defaulttvdbseason=a indicates (absolute) 👍

**Comment by Guslletas** [comment]
Yeah I meant I thought the absolute numbering referred to the absolute number of the episodes within the aired order

**Pull request closed without merging**
