### PR TITLE
Fixed bad mappings in Monogatari Series

### PR DESCRIPTION
**Pull request by cure1245**
Removed duplicate mappings to TV Specials not listed in TVDB

### CODE REVIEW

**Comment by reconman** [comment]
You need to add some `1-0`, otherwise the anidb special episode 1 is mapped to TVDB special 1 for both entries.

**Comment by cure1245** [comment]
The request was already merged. Should I create a new one?

**Comment by sven-7** [comment]
> The request was already merged. Should I create a new one?

Yeah. Go ahead and do that if you can.

**Comment by cure1245** [comment]
#46 is up.

**Pull request merged**
