### PR TITLE
update incorrect types to match anidb

### PR DESCRIPTION
**Pull request by meisnate12**
updating incorrect types to match what they have on anidb

### CODE REVIEW

**Comment by BrutuZ** [comment]
Not a fan of changing movies to something else, even though it matches AniDB types

**Comment by meisnate12** [comment]
Is there a reason you're not a fan of it? As far as I can tell Hama only checks that field for if it's a number, "hentai", or "unknown" and other then that it doesn't care. I don't care that about this change as it doesn't really make a difference for my program, but it seems weird for them to not match what they actually are on Anidb. That's what the docs say it should be.

**Comment by meisnate12** [comment]
There's one that actually charged the type to match Anidb unknown type but that also how the rest of the one are that match that type there's 86 of them overall.

**Comment by BrutuZ** [comment]
No particular reason nor deciding factor, just personal opinion xD

I don't really know how or why those values got there and I wouldn't like changing them to break things for others

Bear in mind it's not my list, I'm just a contributor that was given write access due to the high number of mapping issues\PRs I opened, that's why I'm hesitant with changes that go beyond mappings. Feels like I'm stepping out of my bounds

**Comment by meisnate12** [comment]
I gotcha I'm just going by what the docs say and that's to make it match Anidb if you're not comfortable merging it I guess we will just have to wait for some one else.

**Comment by meisnate12** [comment]
I've also got a bunch more changes coming in the future leading up to me adding a bit more automation to this script like pulling tmdb and IMDb ids from Anidb itself so instead of opening tickets people can update Anidb and it'll eventually get pulled to this list. I'm still working on the code to get it right

**Comment by BrutuZ** [comment]
> automation to this script like pulling tmdb and IMDb ids from Anidb

That sounds awesome. If only they supported TVDB too xD

**Comment by meisnate12** [comment]
i mean they support tmdb shows which can easily be converted to tvdb

**Comment by BrutuZ** [comment]
Why on Earth do so many of those ever had the `defaulttvdbseason` set to begin with? o_O

**Comment by meisnate12** [comment]
Probably because the Readme Doc says `For one-off titles it will be 1` as far as im aware all stand alone one-off titles should have a `1` they only get a `0` if theyre associated with a tvdbid

**Comment by Middlepepper** [comment]
Not to tap on a old discussion, but I'm planning to do some big pulls to fix up the list of Unknown. Should I be following the README and adding AniDb.net type to tvdbid and adding defaulttvdbseason for non series or has the decision been made not to?

**Comment by BrutuZ** [comment]
No one else from @Anime-Lists stepped in to voice their opinion, so no decision

**Comment by Middlepepper** [comment]
So for the bulk pulls I'm doing I should just follow what's in the readme right now?
or just stick with tagging movies only in the tvdb field.?

I'm planning to go through a lot of the unknown.xml so want to save some backtracking if possible.

**Comment by BrutuZ** [comment]
> bulk pulls

*\*sweats profusely\** 😅
Probably readme? At least movies and OVAs are common enough around the list for me to be sure they won't break anything.

**Comment by Middlepepper** [comment]
Yeah sorry for the review work you might be getting..... I've new to Github's workflow so I'm gonna stumble with submitting. I'm trying to reduce anime-list-unknown to just shows not on TVDB as a goal. At least the dataset is getting filled right? 😅

That being said in that case I think we can merge this pull as it follows the readme instructions?

**Pull request closed without merging**
