### PR TITLE
TVDB mapping for Fate/Stay Night: Heaven's Feel movies

### PR DESCRIPTION
**Pull request by BrutuZ**
Wondering if this is a proper update to #5 

https://thetvdb.com/series/fate-stay-night/seasons/official/0
https://anidb.net/a10755
https://www.themoviedb.org/search?query=heaven%27s+feel

### CODE REVIEW

**Comment by reconman** [comment]
The TVDB mapping seems fine, but Hama can't handle multiple IMDB and TMDB ids.

**Comment by BrutuZ** [comment]
Hadn't seen it before either, just added the TMDB ones following the usage for IMDB on #5
What would you suggest, strip them all, keep only the first, create separate entries for each movie (assuming having duplicate `anidbid` is allowed)?

**Comment by BrutuZ** [comment]
@sven-7 what's your take on this?

**Comment by BrutuZ** [comment]
> 
> 
> The TVDB mapping seems fine, but Hama can't handle multiple IMDB and TMDB ids.

@reconman After checking, there are actually several examples of similar cases (below) in the list already (below).
While HAMA might not support it, other software seem to. Maybe something for @ZeroQI to look at?

```diff
@@ 13818 @@
  <anime anidbid="4772" tvdbid="75411" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="tt0936323,tt0936320">
    <name>Rozen Maiden: Ouverture</name>
  </anime>
@@ 14195 @@
  <anime anidbid="4932" tvdbid="82099" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="tt1155650,tt1155651,tt1155652,tt1233474,tt1278060,tt1343089,tt1345776">
    <name>Gekijouban Kara no Kyoukai: The Garden of Sinners</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-2;2-1;3-0;4-0;</mapping>
    </mapping-list>
  </anime>
@@ 17693 @@
  <anime anidbid="6517" tvdbid="142601" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="tt9044262,tt9044260,tt9044268,tt9044266,tt9044272,tt9044264,tt9044270">
    <name>Kidou Senshi Gundam Unicorn</name>
    <supplemental-info>
      <studio>Sunrise</studio>
    </supplemental-info>
  </anime>
@@ 19375 @@
  <anime anidbid="7103" tvdbid="179791" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="tt1663145,tt1679583,tt1726641,tt1753855,tt1809274,tt1865375">
    <name>Break Blade</name>
  </anime>
@@ 20383 @@
  <anime anidbid="7439" tvdbid="movie" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="tt1754177,tt2048804,tt2423504">
    <name>Mardock Scramble</name>
  </anime>
@@ 20601 @@
  <anime anidbid="7507" tvdbid="movie" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="tt1686865,tt2936864">
    <name>Tezuka Osamu no Buddha</name>
  </anime>
@@ 21136 @@
  <anime anidbid="7685" tvdbid="78232" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="tt0100421,tt0100422">
    <name>A-Ko The Versus</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="1">;1-5;2-6;</mapping>
    </mapping-list>
  </anime>
@@ 22949 @@
  <anime anidbid="8311" tvdbid="245451" defaulttvdbseason="0" episodeoffset="3" tmdbid="" imdbid="tt4232272,tt6302292">
    <name>Gekijou Remix Han Appleseed XIII</name>
  </anime>
@@ 30108 @@
  <anime anidbid="10977" tvdbid="275609" defaulttvdbseason="0" episodeoffset="" tmdbid="334361,357413" imdbid="">
    <name>Wake Up, Girls! Zoku Gekijouban</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-3;2-4;</mapping>
    </mapping-list>
  </anime>
@@ 30279 @@
  <anime anidbid="11040" tvdbid="278157" defaulttvdbseason="0" episodeoffset="" tmdbid="347183,347186" imdbid="">
    <name>Gekijouban Haikyuu!!</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;2-4;</mapping>
    </mapping-list>
  </anime>
@@ 33473 @@
  <anime anidbid="12246" tvdbid="Movie" defaulttvdbseason="1" episodeoffset="" tmdbid="431802,431803" imdbid="">
    <name>Koutetsujou no Kabaneri Soushuuhen</name>
  </anime>
@@ 33602 @@
  <anime anidbid="12291" tvdbid="314031" defaulttvdbseason="0" episodeoffset="8" tmdbid="415282,428294,428297" imdbid="">
    <name>Chain Chronicle (2016)</name>
  </anime>
@@ 35503 @@
  <anime anidbid="12982" tvdbid="278157" defaulttvdbseason="0" episodeoffset="" tmdbid="461762,461763" imdbid="">
    <name>Gekijouban Soushuuhen Haikyuu!!</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-6;2-7;</mapping>
    </mapping-list>
  </anime>
@@ 38252 @@
  <anime anidbid="13941" tvdbid="326109" defaulttvdbseason="0" episodeoffset="" tmdbid="526426,526429" imdbid="tt10068158,tt10068544">
    <name>Gekijouban Soushuuhen Made in Abyss</name>
  </anime>
@@ 39089 @@
  <anime anidbid="14239" tvdbid="353666" defaulttvdbseason="0" episodeoffset="5" tmdbid="637202,637462" imdbid="">
    <name>Gekijouban Fate/Grand Order: Shinsei Entaku Ryouiki Camelot</name>
  </anime>

```

**Comment by ZeroQI** [comment]
Double ids? Rare enough but in code already as a ticket was raised since it crashed. Think I use the first one only

**Comment by reconman** [comment]
I'll merge this for now.

**Pull request merged**
