### PR TITLE
Update Detective Conan and Mug Cup mo

### PR DESCRIPTION
**Pull request by krbrs**
Matched Meitantei Conan regular episodes to Seasons (up until last available episode number in TVDB.

Altered Mug Cup mo Specials mapping up until expected episode number count (12 regular planned, so 12 Live Action). If this should be different I will change the mapping in the future

### CODE REVIEW

**Comment by reconman** [comment]
What's the benefit of not using absolute episodes?

**Comment by BrutuZ** [comment]
Didn't notice you had already opened a new PR, so repeating myself on https://github.com/Anime-Lists/anime-lists/pull/56#issuecomment-824997174
> While at it...
```diff
@@ 30513,6 @@
  <anime anidbid="11135" tvdbid="289763" defaulttvdbseason="1" episodeoffset="13" tmdbid="" imdbid="">
    <name>The Idolmaster: Cinderella Girls (2015)</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0" offset="1"/>
    </mapping-list>
  </anime>
```

**Comment by krbrs** [comment]
@reconman
In absolute order only one intro was detected by Plex, the different ones don't show a "Skip Intro" button. In fact the first episodes Plex started recognizing the intro in have that button.

I intended to do this for One Piece as well some time later, if that's not already the case, but now I'm unsure. 

Other separate Anime seasons are merged together to one show and put into seasons. So if this was split up it would follow this schema, even though it's still the same show for all seasons.

I think it depends on how people want it to be sorted in their libraries, right? I can remove that mapping if this is not intended or wanted. I thought "anidb3" override was exactly for things like that?


@BrutuZ
Alright, I will check and fix that too 😄

**Comment by reconman** [comment]
Do you mean tvdb3?

Can you test the current behavior and the one after your change?

**Comment by krbrs** [comment]
There is also anidb3 which I'm using currently - it seems that tvdb3 would maybe solve my issue with the absolute order. But I would have to use the tvdbid in the folder name, correct? I wouldn't be able to create this automatically using shoko server then. 

Anidb3 uses the ANIDB ID (https://github.com/ZeroQI/Absolute-Series-Scanner) but behaves differently to tvdb3.

My Library is currently refreshing the Intro scan for Conan, I will get back to you after it's done.

**Comment by BrutuZ** [comment]
> But I would have to use the tvdbid in the folder name, correct?
Not quite, you just need to fix the match using the force-tag, in this case `[anidb3-266]`
https://github.com/ZeroQI/Absolute-Series-Scanner#forcing-the-movieseries-id

**Comment by krbrs** [comment]
> Not quite, you just need to fix the match using the force-tag, in this case `[anidb3-266]`
Yeah I'm doing this right now. I was asking if it is using the TVDB-ID for tvdb3- force-tag.

**Comment by BrutuZ** [comment]
Sure, `tvdbX` will look for the TVDB ID, `anidbX` will look for AniDB's

**Comment by reconman** [comment]
But anidb3 only changes the specials order according to the documentation?

**Comment by krbrs** [comment]
@BrutuZ you mean like this?:

`  <anime anidbid="266" tvdbid="72454" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
    <name>Meitantei Conan</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-0;2-0;</mapping>
      <mapping anidbseason="1" tvdbseason="2" start="29" end="54" offset="-28"></mapping>
      <mapping anidbseason="1" tvdbseason="3" start="55" end="82" offset="-54"></mapping>
      <mapping anidbseason="1" tvdbseason="4" start="83" end="106" offset="-82"></mapping>`

and so on?

**Comment by reconman** [comment]
anidb2 and 3 are for many anidb entries for 1 tvdb entry. In this case it's a one to one mapping.

Also, I don't think that anime-list or ASS has anything to do with intro detection.

**Comment by krbrs** [comment]
> Also, I don't think that anime-list or ASS has anything to do with intro detection.

Indirectly - if it's only 1 Season with all different intros, not all of them are detected.
In different seasons it is working (my rescan just finished and I confirmed this behavior) - I don't know how this works within plex but I think it scans the Intro for one season and tries to find the same audio part - only those matching get the "skip intro" button

**Comment by BrutuZ** [comment]
Since intro detection scans every file individually, would be weird to limit the matches to a season. But then again we're talking about Plex and I wouldn't put any silly behavior past them 😂

**Review by reconman — APPROVED** [review]

**Comment by BrutuZ** [comment]
I know this is done and closed, but just pointing out that `tvdb2` uses TheTVDB's own mapping of absolute episode number to seasons, basically the same you've done manually here and on #63.

**Comment by reconman** [comment]
Difference between tvdb and anidb formats is the directory structure. For anidb you have 1 folder for each AniDB entry, for TVDB you have to either use season folders or use SxEx file names.

I personally use season folders AND SxEx file names right now, even for single season series.

**Comment by BrutuZ** [comment]
Indeed, but if the episodes are within a single entry both in AniDB and TheTVDB like One Piece and Detective Conan, there's no need to map the seasons in the file. `thetvdb2` should match and split into seasons inside Plex without further internal mapping.

**Comment by krbrs** [comment]
For me it's impossible to automate everything like it is now using tvdb2.

I have shoko move anime to the destination folders after download. It creates the folder and adds the forced anidb-id to the foldername, if the folder does not yet exist. I think it's not possible to automatically fetch the tvdb-id via shoko from
AniDB - so this would destroy my "download-and-move-to-plex" automations. I just want new episodes to show up where they belong without further manual intervention :)

**Comment by BrutuZ** [comment]
Took a look at Shoko and seems besides AniDB, it also matches TheTVDB, TMDB and Trakt. I didn't delve too deep into it because the docs for the desktop application (and its renaming module) was 404, but maybe there are TheTVDB tags available.

**Comment by krbrs** [comment]
Yeah right now they try to match entries to TVDB. they don't fetch an ID from AniDB but try and scrobble by series name.
If you find a wrong match you have to fix it by yourself. Since matching takes place by hashes via AniDB, this is more reliable. I don't know if the renamer would support the TVDB ID while adding/renaming, since the matching takes place when the file is recognized and TVDB occurs later in shoko.

But that aside - have been talking to the devs about TVDB: they are going to drop support for TVDB because of the costs for the upcoming API. They are transitioning to something they create and TMDB.

**Pull request merged**
