### PR TITLE
Added Cike Wu Liuqi fix

### PR DESCRIPTION
**Pull request by Curros**
| AniDB | TVDB/TMDB/IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/14288 | https://thetvdb.com/series/killer-seven <br/> https://www.imdb.com/title/tt10384610/ <br/> https://www.themoviedb.org/tv/79141 |  s01 s02 s03 s04 |

### CODE REVIEW

**Comment by BrutuZ** [comment]
> *   **tmdbid**/**imdbid** - TheMovieDB.org/imdb.com ID. Only used for standalone entries like movies.
    Multiple IDs can be mapped to the same AniDB entry with comma sepparation. Ex: `tmdbid="12345,67890"`, `imdbid="tt12345678,tt9876543"`
    **[Do not use tmdbid for series!](https://github.com/ScudLee/anime-lists/issues/342)**

**Comment by Curros** [comment]
> > * **tmdbid**/**imdbid** - TheMovieDB.org/imdb.com ID. Only used for standalone entries like movies.
> >   Multiple IDs can be mapped to the same AniDB entry with comma sepparation. Ex: `tmdbid="12345,67890"`, `imdbid="tt12345678,tt9876543"`
> >   **[Do not use tmdbid for series!](https://github.com/ScudLee/anime-lists/issues/342)**

It was working OK on local, hope now is OK, thanks for the info.

**Comment by BrutuZ** [comment]
Those fields are reserved to movie mappings, series "shouldn't" be affected by them.
If you're using HAMA you'd only see the effects on a movie library, they'd all merge into the same entry as additional file versions. However, not all parsers are built equally, some might look for those entries first and decide whether the entry is a movie based on the presence of those fields, not to mention consistency and the issue linked

**Comment by Curros** [comment]
@BrutuZ thanks for the thorough explanation.

**Pull request merged**
