### PR TITLE
Map `Dead Dead Demon's Dededededestruction` as other order

### PR DESCRIPTION
**Pull request by plantysnake**
| AniDB | TVDB/TMDB/IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/17273 | https://thetvdb.com/index.php?tab=series&id=418123 | Mapping `Dead Dead Demon's Dededededestruction` as other order |

### CODE REVIEW

**Review by BrutuZ — CHANGES_REQUESTED** [review]
Keep the TMDB IDs. The linked issue does not apply as they are movie IDs, _not_ series IDs

https://www.themoviedb.org/movie/1172228
https://www.themoviedb.org/movie/117229

**Comment by BrutuZ** [comment]
I'm confused, how did 4 "Other" Episodes turn into 18 mappings?

**Comment by plantysnake** [comment]
18 episodes are announced

**Comment by BrutuZ** [comment]
Ah, got it, I see no problem with it then.

Do you know if it's the same content of the original Movies just split into episodes? If so, might be worth adding something like
```xml
<mapping anidbseason="1" tvdbseason="1">;1-1+2+3+4+5+6+7+8+9;2-10+11+12+13+14+15+16+17+18;</mapping>
```
To also cover the original version as a series if someone fancies that.

**Comment by plantysnake** [comment]
I believe it's the same as Demon Slayer Mugen Train
Same things with some additional scenes

**Pull request merged**
