### PR TITLE
Remove bad defaulttvdbseason

### PR DESCRIPTION
**Pull request by meisnate12**
Noticed a couple of incorrect `defaulttvdbseason` this corrects that

### CODE REVIEW

**Comment by BrutuZ** [comment]
First ones will break somewhere else instead without the episode offset

**Comment by meisnate12** [comment]
thats pretty generic. what's gonna break and why is it only that show? I can remove them if need but I'd love to know why as im working on a program to scrap and check the ids on this list (you're gonna see more of me over the next little bit lol) so i really need to know the reasons for little things like this. If you have Discord I'd love to chat about some specifics of this list. You can easily find me in the Plex Meta Manager Discord.

**Comment by BrutuZ** [comment]
"Break" was a poor choice of words. It's bad in a different way, while 99 makes no sense and points nowhere, having 3 AniDB entries pointing to the same TVDB ID and Season without and episode offset means they all point to S00E01.
So if someone does have all of those episodes, instead of getting no metadata due to season 99, they will all merge in a single entry for S00E01, which isn't right for any of them.

**Comment by meisnate12** [comment]
easy fix instead of leaving the stupid 99 ill just add in the proper episode offset

**Comment by meisnate12** [comment]
ok pushed that change i also had one other one of id i noticed and fixed

**Comment by BrutuZ** [comment]
Taking Irvine as an example: It's Episode 5 on TVDB and Episode 01 on AniDB, so the offset would be 4 (TVDB - AniDB)

The "final" number is used for individual episodes in `mapping-list`

**Comment by meisnate12** [comment]
gotcha pushed that fix also pushed normalizing tvdbid types ie (`Movie` -> `movie`, `ova` -> `OVA`, `tv special` -> `tvspecial`, and `Web` -> `web`)

**Comment by BrutuZ** [comment]
These entries without a TVDB ID but somehow with a TVDB Season really puzzle me o_O
Unrelated to your commit, just felt like venting it out xD

**Comment by meisnate12** [comment]
oh its getting to me too the more i look the more i want to fix haha

**Pull request merged**
