### PR TITLE
add tmdbid for a few one-shot-productions

### PR DESCRIPTION
**Pull request by winterbird-code**
This may be a bit controversial since  these titles have a tvdb series entries, and thus fail the last part of the "One-off titles that won't ever be added to theTVDB.com"-test, so this is more of a personal view that single episode entries which are not related to a multi-episode series should be categorized as movies. I will also argue that TMDB has better entries for these titles (although barely). 

While these titles do have a corresponding tvdb series entry they are the one single episode registered for them; and there is no reason to  beleive that will change. Because of that I will argue that these belong to the Movie catagory.

I do note that Jikuu Bouken Nuumamonger (aka. Chrono Trigger) *does* have an extra "special" episode in TVDB,
but everything about it is unknown except for the runtime which is the same as the main entry. After a very brief research it seems this animation was mostly a promo video for the video game; shown at a festival in -96 and distributed on VHS in very limited numbers. Rips of the VHS is availabe, but no mention of any special features from them. Until proven otherwise I will assume that the TVDB special entry is a mistake.

| AniDB | TVDB/TMDB/IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/3333 | https://thetvdb.com/index.php?tab=series&id=262314  <br /> https://www.themoviedb.org/movie/262314 | One episode TVDB entry |
| https://anidb.net/anime/10114 | https://thetvdb.com/index.php?tab=series&id=357271  <br /> https://www.themoviedb.org/movie/357271 | One episode TVDB entry |
| https://anidb.net/anime/633 | https://thetvdb.com/index.php?tab=series&id=97781  <br /> https://www.themoviedb.org/movie/97781 | One episode TVDB entry (except for the special which is most likely a mistake) |

### CODE REVIEW

**Comment by BrutuZ** [comment]
There's no need to remove the TVDB ID, an entry can have IDs for all 3 providers.
The client should know beforehand which ID type (series or movie) to parse. On HAMA for example, that's defined by the library type

**Comment by winterbird-code** [comment]
In my use case I actually use these IDs to [determine which library to put the files in](https://github.com/winterbird-code/adbb/blob/master/JELLYFIN.md), so if it has a TVDB ID it will go to the TV Series library, even in these (very few) cases where it would be preferable to have them in the Movie library.

It is a valid point that it's probably in the projects interest to keep the rules simple: To provide all mappings that is possible. I'll leave this as is for a little while just in case someone else wants to comment, otherwise I'll amend this in  a few days to restore the tvdb ids

**Comment by winterbird-code** [comment]
Oops, I accidentally did a force push that removed that file, but it's restored now so the link works.

I don't mind for example the One Piece movies being sorted as special episodes in the One Piece TV Series. They are related after all. These are the only three entries from my collection that are registered as TV Series despite just having one episode, no relation to any other series, and extremely unlikely to get sequels. 

But the more I think about it the more I agree that this is the wrong approach; it's not up to the anime-list to judge what tvdb decides to be a tv-series or not; it should just map the ID:s. I'll get back to this in a day or two and restore the tvdb ids and just make this a PR for adding tmdb ids.

**Comment by BrutuZ** [comment]
TVDB is finicky enough as it is, arbitrarily deciding what does and does not qualify as specials, whether a spin-off series gets its own entry or is demoted to just another season, removing and reordering entries out of the blue, etc... based on heavens knows what criteria 😠
The list doesn't need to add more confusion to their mess 😅

**Comment by winterbird-code** [comment]
Agree; I've restored the TVDB ID:s, so now the change is just that I've added TMDB IDs to them as well.

**Pull request merged**
