### PR TITLE
Adds fix movies

### PR DESCRIPTION
**Pull request by Arial-Z**
| AniDB | IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/419 | https://www.imdb.com/title/tt0098202 |  |
| https://anidb.net/anime/990 | https://www.imdb.com/title/tt0190641 | old id redirect to this new one  |
| https://anidb.net/anime/991 | https://www.imdb.com/title/tt0287635 | old id redirect to this new one  |
| https://anidb.net/anime/992 | https://www.imdb.com/title/tt0235679 | old id redirect to this new one  |
| https://anidb.net/anime/1070 | https://www.imdb.com/title/tt0142239 | old id redirect to this new one  |
| https://anidb.net/anime/3392 | https://www.imdb.com/title/tt2330912 |  |
| https://anidb.net/anime/4165 | https://www.imdb.com/title/tt5914194 |  |
| https://anidb.net/anime/4168 | https://www.imdb.com/title/tt5911148 |  |
| https://anidb.net/anime/4169 | https://www.imdb.com/title/tt6467156 |  |
| https://anidb.net/anime/4199 | https://www.imdb.com/title/tt1000095 | old id redirect to this new one  |
| https://anidb.net/anime/5048 | https://www.imdb.com/title/tt1226251 | old id redirect to this new one  |
| https://anidb.net/anime/7991 | https://www.imdb.com/title/tt2210479 https://www.imdb.com/title/tt2358911 https://www.imdb.com/title/tt2358913 |  |
| https://anidb.net/anime/8090 | https://www.imdb.com/title/tt1776196 |  |
| https://anidb.net/anime/8146 | https://www.imdb.com/title/tt3355694 |  |
| https://anidb.net/anime/8147 | https://www.imdb.com/title/tt3355698 |  |
| https://anidb.net/anime/8826 | https://www.imdb.com/title/tt2549540 |  |
| https://anidb.net/anime/9125 | https://www.imdb.com/title/tt3392330 | Wrong ID  |
| https://anidb.net/anime/9655 | https://www.imdb.com/title/tt3300814 |  |
| https://anidb.net/anime/9658 | https://www.imdb.com/title/tt2636124 https://www.imdb.com/title/tt3017864 https://www.imdb.com/title/tt3579524 https://www.imdb.com/title/tt4016942 |  |
| https://anidb.net/anime/10318 | https://www.imdb.com/title/tt3918368 |  |
| https://anidb.net/anime/10458 | https://www.imdb.com/title/tt7386590 |  |
| https://anidb.net/anime/10764 | https://www.imdb.com/title/tt4307880 https://www.imdb.com/title/tt5216534 https://www.imdb.com/title/tt5468014 https://www.imdb.com/title/tt5468016 https://www.imdb.com/title/tt5468018 https://www.imdb.com/title/tt5468022 |  |
| https://anidb.net/anime/10966 | https://www.imdb.com/title/tt4503906 |  |
| https://anidb.net/anime/11265 | https://www.imdb.com/title/tt5234428 https://www.imdb.com/title/tt5234458 https://www.imdb.com/title/tt5234462 |  |
| https://anidb.net/anime/11680 | https://www.imdb.com/title/tt5923132 |  |
| https://anidb.net/anime/12754 | https://www.imdb.com/title/tt10635042 |  |
| https://anidb.net/anime/12988 | https://www.imdb.com/title/tt7480958 https://www.imdb.com/title/tt9266078 https://www.imdb.com/title/tt11951334 |  |
| https://anidb.net/anime/13108 | https://www.imdb.com/title/tt11410450 https://www.imdb.com/title/tt11433900 https://www.imdb.com/title/tt14446300 https://www.imdb.com/title/tt18973304 https://www.imdb.com/title/tt18973450 |  |
| https://anidb.net/anime/13175 | https://www.imdb.com/title/tt13276012 |  |
| https://anidb.net/anime/13405 | https://www.imdb.com/title/tt12439248 |  |
| https://anidb.net/anime/13409 | https://www.imdb.com/title/tt7456468 |  |
| https://anidb.net/anime/13482 | https://www.imdb.com/title/tt8925234 |  |
| https://anidb.net/anime/14064 | https://www.imdb.com/title/tt8354164 https://www.imdb.com/title/tt14031960 |  |
| https://anidb.net/anime/14167 | https://www.imdb.com/title/tt11417856 |  |
| https://anidb.net/anime/14415 | https://www.imdb.com/title/tt14531302 https://www.imdb.com/title/tt19849494 |  |
| https://anidb.net/anime/14782 | https://www.imdb.com/title/tt11151982 |  |
| https://anidb.net/anime/14883 | https://www.imdb.com/title/tt11427380 |  |
| https://anidb.net/anime/14949 | https://www.imdb.com/title/tt10540510 |  |
| https://anidb.net/anime/14965 | https://www.imdb.com/title/tt15762470 |  |
| https://anidb.net/anime/14993 | https://www.imdb.com/title/tt11819890 |  |
| https://anidb.net/anime/15100 | https://www.imdb.com/title/tt12350118 https://www.imdb.com/title/tt13308788 |  |
| https://anidb.net/anime/15198 | https://www.imdb.com/title/tt11142308 |  |
| https://anidb.net/anime/15204 | https://www.imdb.com/title/tt13344602 |  |
| https://anidb.net/anime/15235 | https://www.imdb.com/title/tt11193002 |  |
| https://anidb.net/anime/15253 | https://www.imdb.com/title/tt10734928 |  |
| https://anidb.net/anime/15308 | https://www.imdb.com/title/tt11433874 |  |
| https://anidb.net/anime/15373 | https://www.imdb.com/title/tt11958344 |  |
| https://anidb.net/anime/15414 | https://www.imdb.com/title/tt13139218 |  |
| https://anidb.net/anime/15450 | https://www.imdb.com/title/tt13871024 |  |
| https://anidb.net/anime/15481 | https://www.imdb.com/title/tt15801642 |  |
| https://anidb.net/anime/15506 | https://www.imdb.com/title/tt15607440 |  |
| https://anidb.net/anime/15565 | https://www.imdb.com/title/tt12367916 |  |
| https://anidb.net/anime/15585 | https://www.imdb.com/title/tt12439268 |  |
| https://anidb.net/anime/15633 | https://www.imdb.com/title/tt13385804 |  |
| https://anidb.net/anime/15722 | https://www.imdb.com/title/tt13064272 |  |
| https://anidb.net/anime/15829 | https://www.imdb.com/title/tt13409496 |  |
| https://anidb.net/anime/15852 | https://www.imdb.com/title/tt13740078 |  |
| https://anidb.net/anime/15869 | https://www.imdb.com/title/tt15715792 |  |
| https://anidb.net/anime/16064 | https://www.imdb.com/title/tt15052770 |  |
| https://anidb.net/anime/16091 | https://www.imdb.com/title/tt14228078 |  |
| https://anidb.net/anime/16180 | https://www.imdb.com/title/tt14702778 https://www.imdb.com/title/tt27272779 |  |
| https://anidb.net/anime/16379 | https://www.imdb.com/title/tt14837960 |  |
| https://anidb.net/anime/16401 | https://www.imdb.com/title/tt15610384 |  |
| https://anidb.net/anime/16427 | https://www.imdb.com/title/tt15392166 |  |
| https://anidb.net/anime/16434 | https://www.imdb.com/title/tt15783458 |  |
| https://anidb.net/anime/16439 | https://www.imdb.com/title/tt15801562 | Wrong id show instead of movie  |
| https://anidb.net/anime/16702 | https://www.imdb.com/title/tt15428330 |  |
| https://anidb.net/anime/16706 | https://www.imdb.com/title/tt15439344 |  |
| https://anidb.net/anime/16707 | https://www.imdb.com/title/tt15450826 |  |
| https://anidb.net/anime/16801 | https://www.imdb.com/title/tt15494038 |  |
| https://anidb.net/anime/16963 | https://www.imdb.com/title/tt17677744 https://www.imdb.com/title/tt25010142 |  |
| https://anidb.net/anime/17009 | https://www.imdb.com/title/tt19770970 |  |
| https://anidb.net/anime/17040 | https://www.imdb.com/title/tt17382524 |  |
| https://anidb.net/anime/17151 | https://www.imdb.com/title/tt21970564 |  |
| https://anidb.net/anime/17176 | https://www.imdb.com/title/tt22746976 |  |

### CODE REVIEW

**Comment by BrutuZ** [comment]
Was this filled with a script? If so, any chance to have it fill the media type from AniDB on `tvdbid` and `defaulttvdbseason=1` on the empty\unknown ones? 🥺

**Comment by Arial-Z** [comment]
no this was done by hand, but i can update them like this if needed
`<anime anidbid="419" tvdbid="OVA" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="tt0098202">`

**Comment by BrutuZ** [comment]
Ideally since that would clean them up from other list files ([anime-list-unknown.xml](https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-unknown.xml) and [anime-list-todo.xml](https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-todo.xml)).
I asked about the script because it would affect over half the entries (40+ / 75) that have `tvdbid` either empty or unknown (https://github.com/Anime-Lists/anime-lists#anime-list-masterxml-1). `defaulttvdbseason=1` for those despite not having a valid ID number (for consistency's sake, was already like that when I got here)

**Comment by BrutuZ** [comment]
I don't really get *why* entries with a media type \ `unknown` TVDBID have `1` set as their `defaulttvdbseason`, doesn't really make sense to me either but most entries were already like that so I try to keep it consistent 😅

**Pull request merged**
