### PR TITLE
Update anime-list-master.xml

### PR DESCRIPTION
**Pull request by krbrs**
Fixed Mapping of Idolmaster Cinderella Girls Gekijou S01-S04 Specials

### CODE REVIEW

**Comment by reconman** [comment]
There were some mistakes in your PR, but why did you close it?

**Comment by krbrs** [comment]
I think I made a mistake with the First Season of the Specials Order and missed the Special Episodes 41-43. Should i reopen it or make another commit?

**Comment by reconman** [comment]
You've already deleted your branch, so you probably have to create a new PR from that new branch.

If you detect errors in your PR, you can change it to a draft instead: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

I noticed that episodes 14-16 of the first entry's specials can now be linked to episodes 44-46 of TVDB season 0 instead.

Please thoroughly check the anidb special episode names against those in TVDB season 0.

**Comment by krbrs** [comment]
Thank you I will use the draft function the next time I'm working on my branch and already made a pull request.
I noticed that I missed the episodes you mentioned, those will be included in my new request :)

Does this have to be 14-41,15-42,16-43 or can it be like this:

<mapping anidbseason="0" tvdbseason="0" start="14" end="16" offset="40"/> ?

**Comment by reconman** [comment]
You need to put ` characters around your mapping element in order to be able to see it on Github.

I think it has to be in the first form, but I didn't come up with the mapping format and the one who did vanished.

**Pull request closed without merging**
