### PR TITLE
Fixed mappings for Initial D extra titles

### PR DESCRIPTION
**Pull request by 1LucKyLuke**
Fixes mappings for 

- Initial D Extra Stage
- Initial D Extra Stage 2
- Initial D Battle Stage
- Initial D Battle Stage 2

### CODE REVIEW

**Comment by reconman** [comment]
Aren't the other specials also affected by the 1 extra episode?

**Comment by 1LucKyLuke** [comment]
The mapping-list entry for the Legends movies are correct. Could be changed to use episodeoffset though.
One question here: That entry has multiple imdb ids. Is that even supported?

**Comment by reconman** [comment]
I'm only using Hama, which completely ignores imdb. Probably only the Kodi plugin uses that attribute and I have no idea how the code looks like.

**Comment by 1LucKyLuke** [comment]
Ok, since I'm also only using Hama I'm not gonna touch that.

**Pull request merged**
