### PR TITLE
Gundam witch part 2 map

### PR DESCRIPTION
**Pull request by Boontato**
| AniDB | TVDB/TMDB/IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/17648 | https://thetvdb.com/index.php?tab=series&id=324710 | Season 2 |

### CODE REVIEW

**Comment by BrutuZ** [comment]
These `Update anime-list-master.xml` and `Merge branch 'Anime-Lists:master'` on your PRs always puzzle me

**Comment by Boontato** [comment]
ahha sorry
also someone on the tvdb is changing gundam witch season 2 between continuing season 1 and a new season 2. might need to be fixed again

**Comment by BrutuZ** [comment]
So annoying when they go on these reorganization sprees 😓

**Comment by Boontato** [comment]
Also I think the weird update and merge things are because my GitHub desktop? Or whatever setting I have is not correct. I'll have to remake the fork to clean out the history anyway.

**Pull request merged**
