### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by BrutuZ**
Thought about updating the readme a little, mostly by linking HAMA and rearranging some items.

PR open for opinions, suggestions, etc...

### CODE REVIEW

**Comment by meisnate12** [comment]
This list is also used to create [Plex Meta Manager Anime IDs](https://github.com/meisnate12/Plex-Meta-Manager-Anime-IDs) for [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager)

It's also used to create [anime-lists](https://github.com/Fribb/anime-lists) for [MyAnimeList Plex Metadata Agent](https://github.com/Fribb/MyAnimeList.bundle)

**Comment by meisnate12** [comment]
Also I'd consider putting a warning saying the tvdb id must be a show ID not a movie, season, or episode id

**Comment by BrutuZ** [comment]
Thanks, added both projects to the list and included a note regarding TVDB movies.

**Comment by meisnate12** [comment]
for tvdbid can you list out the expected types ie `movie`, `OVA`, `hentai`, `tv special`, `unknown`, `music video`, `web`, and `other`

**Comment by BrutuZ** [comment]
Doesn't look necessary, it already mentions the AniDB Type should be used
> One-off titles that won't ever be added to theTVDB.com (movies, TV specials, one-shot OVAs)
    are marked by their AniDb.net type, unless they can be associated to a multi-episode series (in which case they use the corresponding theTVDB.com id or "unknown").

That's easy enough to spot on the main Info table image and anyone curious about all the available types should be able to find the list easily enough, took me a couple minutes at most to reach https://wiki.anidb.net/Anime_Type

**Comment by meisnate12** [comment]
I agree it's not hard to tell but people have added the wrong values before and I'm sure they will again. It doesn't hurt to add clarity directly to the readme of the list they want to edit.

**Pull request merged**
