### PR TITLE
Added Owarimonogatari and HTN

### PR DESCRIPTION
**Pull request by Larvitar**

### CODE REVIEW

**Comment by sven-7** [comment]
How broken does Owarimonogatri appear to you without this mapping? @reconman removed it a few days ago, so since it's being put back in so quickly, I'm assuming something broke,

**Comment by sven-7** [comment]
I'm going to merge in for the time being.

**Comment by reconman** [comment]
The AniDB and TVDB entries don't match together at all, leave them unmapped.

**Comment by sven-7** [comment]
Reverted, but I added Houkago Teibou Nisshi in again. So that is done for now.

**Comment by Larvitar** [comment]
> The AniDB and TVDB entries don't match together at all, leave them unmapped.

They do. Problem with 2017 season is that it was released in 2 versions - 3 episode version, and 7 episode one (2 + 3 + 3). This might make episode matching tricky, but I'm not sure how `AniDB.net Scraper Mods` handles it. But only episodes can't be directly matched easily (aniDB for some reason lists 1. and 2. episode as the same, so only 2 episodes there), series itself directly matches to tvdb S5

**Comment by Larvitar** [comment]
Also AniDB list those 7 episodes as O1-O2, O3-O5 and O7-O9 which matches TVDBs S5 episodes 1-7

**Comment by reconman** [comment]
See #47 

And your version would map AniDB episode 1 to TVDB episode 1.

The only way you could use defaulttvdbseason="5" is by mapping everything to TVDB episode 0, but I don't know if that will bring any benefit.

**Comment by Larvitar** [comment]
hmm. Maybe that's what we should do. At least we'd get a proper series matching which then would allow Hama etc. to at least pull HD images from tvdb/fanart.

**Comment by reconman** [comment]
That's what I did just now. But as someone who does have Monogatari in their Plex library, I had to manage the posters myself since TVDB is treating half the episodes as specials.

**Comment by Larvitar** [comment]
Thanks :). 
Actually I use Jellyfin with a plugin I wrote for myself and use the mapping just to get high quality images from theTVDB so it's kind of important for me.

**Pull request merged**
