### PR TITLE
Map multiple anidb entries to tvdb ids

### PR DESCRIPTION
**Pull request by plantysnake**
| AniDB | TVDB/TMDB/IMDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/309     | https://thetvdb.com/index.php?tab=series&id=358536 | Season 1 `Choukou Tenshi Escalayer` tvdb map |
| https://anidb.net/anime/614     | https://thetvdb.com/index.php?tab=series&id=401051 | Season 1 `Ryuuki Denshou` tvdb map |
| https://anidb.net/anime/1331   | https://thetvdb.com/index.php?tab=series&id=260798 | Season 1 `Manami & Nami Sprite` tvdb map |
| https://anidb.net/anime/2788   | https://thetvdb.com/index.php?tab=series&id=395530 | Season 1 `Tokyo Daigaku Monogatari` tvdb partial map |
| https://anidb.net/anime/5931   | https://thetvdb.com/index.php?tab=series&id=423173 | Season 1 `Shoujo Sect: Innocent Lovers` tvdb map |
| https://anidb.net/anime/7915   | --- | Marked `Ane Jiru 2 The Animation: Shirakawa San Shimai ni Omakase` as `hentai` |
| https://anidb.net/anime/7916   | --- | Marked `Fighting of Ecstasy` as `hentai` |
| https://anidb.net/anime/7923   | --- | Marked `Bust to Bust: Chottokurai Kusatteru no ga Umaindesu yo?` as `hentai` |
| https://anidb.net/anime/7928   | --- | Marked `Onna Spy Goumon: Teki no Ajito wa Jotai Goumonsho` as `hentai` |
| https://anidb.net/anime/7929   | --- | Marked `Kanojo ga Mimai ni Konai Wake` as `hentai` |
| https://anidb.net/anime/7970   | --- | Marked `Elf-hime Nina` as `hentai` |
| https://anidb.net/anime/7980   | --- | Marked `Kyouiku Shidou The Animation` as `hentai` |
| https://anidb.net/anime/7981   | --- | Marked `Miyazaki Maya Daizukan` as `hentai` |
| https://anidb.net/anime/7988   | --- | Marked `Aisai Nikki` as `hentai` |
| https://anidb.net/anime/7998   | --- | Marked `Ore wa Kanojo o Shinjiteru!` as `hentai` |
| https://anidb.net/anime/8241   | --- | Marked `Onanie` as `hentai` |
| https://anidb.net/anime/8261   | --- | Marked `Cosplay Roshutsu Kenkyuukai` as `hentai` |
| https://anidb.net/anime/8263   | --- | Marked `Kyuuketsuki` as `hentai` |
| https://anidb.net/anime/8493   | --- | Marked `Wizard Girl Ambitious` as `hentai` |
| https://anidb.net/anime/12157 | --- | Marked `Enkou Shoujo: Rikujoubu Yukki no Baai The Animation` as `hentai` |
| https://anidb.net/anime/12158 | https://thetvdb.com/index.php?tab=series&id=314349 | Season 1 `Mahou Shoujo? Naria Girls` tvdb map |
| https://anidb.net/anime/12228 | https://thetvdb.com/index.php?tab=series&id=265386 | Season 0 Episode 8 `Puchimas!! Petit Petit Idolmaster: Fuyu-->Kotatsu<--Haru` tvdb map |
| https://anidb.net/anime/12396 | --- | Marked `Bokura no Sex` as `hentai` |
| https://anidb.net/anime/13144 | https://thetvdb.com/index.php?tab=series&id=265386 | Season 0 Episodes 9-10 `Puchimas! Petit Idolmaster` tvdb map |
| https://anidb.net/anime/13402 | https://thetvdb.com/index.php?tab=series&id=334707 | Season 1 `Omiai Aite wa Oshiego, Tsuyoki na, Mondaiji.` tvdb map |
| https://anidb.net/anime/13730 | --- | Marked `Enkou JK Bitch Gal: Oji-san to Nama Pako Seikatsu` as `hentai` |
| https://anidb.net/anime/13769 | --- | Marked `OVA Muttsuri Do Sukebe Ro Gibo Shimai no Honshitsu Minuite Sex Zanmai` as `hentai` |
| https://anidb.net/anime/13972 | https://thetvdb.com/index.php?tab=series&id=349733 | Season 1 `Yarichin Bitch Bu` tvdb map |
| https://anidb.net/anime/14698 | https://thetvdb.com/index.php?tab=series&id=360675 | Season 1 `Araiya-san! Ore to Aitsu ga Onnayu de!?` tvdb map |
| https://anidb.net/anime/14924 | https://thetvdb.com/index.php?tab=series&id=364542 | Season 1 `Yubisaki kara Honki no Netsujou: Osananajimi wa Shouboushi` tvdb map |
| https://anidb.net/anime/15274 | https://thetvdb.com/index.php?tab=series&id=373728 | Season 1 `Overflow` tvdb map |
| https://anidb.net/anime/15403 | https://thetvdb.com/index.php?tab=series&id=379925 | Season 1 `Ore no Yubi de Midarero. Heitengo Futarikiri no Salon de...` tvdb map |
| https://anidb.net/anime/15447 | https://thetvdb.com/index.php?tab=series&id=382658 | Season 1 `Kyojin-zoku no Hanayome` tvdb map |
| https://anidb.net/anime/15630 | https://thetvdb.com/index.php?tab=series&id=389232 | Season 1 `Eternity: Shin'ya no Nurekoi Channel` tvdb map |
| https://anidb.net/anime/15697 | https://thetvdb.com/index.php?tab=series&id=389474 | Season 1 `Otona Nya Koi no Shikata ga Wakaranee!` tvdb map |
| https://anidb.net/anime/15855 | https://thetvdb.com/index.php?tab=series&id=397070 | Season 1 `Jimihen!! Jimiko o Kae Chau Jun Isei Kouyuu` tvdb map |
| https://anidb.net/anime/16016 | https://thetvdb.com/index.php?tab=series&id=364542 | Season 2 `Yubisaki kara Honki no Netsujou 2: Koibito wa Shouboushi` tvdb map |
| https://anidb.net/anime/16057 | https://thetvdb.com/index.php?tab=series&id=410768 | Season 1 `Maou Evelogia ni Mi o Sasageyo` tvdb map |
| https://anidb.net/anime/16385  | https://thetvdb.com/index.php?tab=series&id=412880 | Season 1 `Ouji no Honmei wa Akuyaku Reijou` tvdb map |
| https://anidb.net/anime/16543  | https://thetvdb.com/index.php?tab=series&id=424562 | Season 1 `Showtime! Uta no Onee-san Datte Shitai` tvdb map |
| https://anidb.net/anime/16681 | https://thetvdb.com/index.php?tab=series&id=400398 | Season 3 `Cardfight!! Vanguard: Will+Dress` tvdb map |
| https://anidb.net/anime/16686 | --- | Marked `Abandon: 100 Nuki Shinai to Derarenai Fushigi na Kyoushitsu` as `hentai` |
| https://anidb.net/anime/16792 | https://thetvdb.com/index.php?tab=series&id=410425 | Season 1 `Eiyuu Kyoushitsu` tvdb map |
| https://anidb.net/anime/16794 | https://thetvdb.com/index.php?tab=series&id=414907 | Season 1 `Estab Life: Great Escape` tvdb map |
| https://anidb.net/anime/16795 | https://thetvdb.com/index.php?tab=series&id=410466 | Season 1 `Kotarou wa Hitorigurashi` tvdb map |
| https://anidb.net/anime/16797 | --- | Marked `Girls Rush The Animation` as `hentai` |
| https://anidb.net/anime/16799 | --- | Marked `Kono Kaisha... Nanika Okashii!` as `hentai` |
| https://anidb.net/anime/16806 | --- | Marked `Yamitsuki Pheromone The Animation` as `hentai` |
| https://anidb.net/anime/16808 | https://thetvdb.com/index.php?tab=series&id=415656 | Season 1 `Petit Seka` tvdb map |
| https://anidb.net/anime/16827 | https://thetvdb.com/index.php?tab=series&id=415138 | Season 1 `Sugar Apple Fairy Tale` tvdb map |
| https://anidb.net/anime/16829 | --- | Marked `Papa Katsu!` as `hentai` |
| https://anidb.net/anime/16913 | --- | Marked `Akane wa Tsumare Somerareru` as `hentai` |
| https://anidb.net/anime/16926 | https://thetvdb.com/index.php?tab=series&id=385278 | Season 2 `Ijiranaide, Nagatoro-san 2nd Attack` tvdb map |
| https://anidb.net/anime/16934 | https://thetvdb.com/index.php?tab=series&id=416764 | Season 1 `3 Byou Go, Yajuu. Goukon de Sumi ni Ita Kare wa Midara na Nikushoku Deshita` tvdb map |
| https://anidb.net/anime/16945 | --- | Marked `Ero Ishi: Seijun Bishoujo o Kotoba Takumi ni Hametai Houdai` as `hentai` |
| https://anidb.net/anime/16950 | https://thetvdb.com/index.php?tab=series&id=413411 | Season 1 `Irodorimidori (2022)` tvdb map |
| https://anidb.net/anime/16953 | https://thetvdb.com/index.php?tab=series&id=414107 | Season 1 `Delicious Party Precure` tvdb map |
| https://anidb.net/anime/16956 | https://thetvdb.com/index.php?tab=series&id=400015 | Season 2 `Kyuuketsuki Sugu Shinu 2` tvdb map |
| https://anidb.net/anime/16962 | https://thetvdb.com/index.php?tab=series&id=398544 | Season 2 `Seirei Gensouki 2` tvdb map |
| https://anidb.net/anime/16968 | --- | Marked `Otaku ni Yasashii Gal toka, Kyonyuu no Osananajimi toka.` as `hentai` |
| https://anidb.net/anime/16984 | https://thetvdb.com/index.php?tab=series&id=412843 | Season 1 `Yowai 5000-nen no Soushoku Dragon, Iwarenaki Jaryuu Nintei` tvdb map |
| https://anidb.net/anime/16999 | https://thetvdb.com/index.php?tab=series&id=424562 | Season 2 `Showtime! Uta no Onee-san Datte Shitai 2` tvdb map |
| https://anidb.net/anime/17003 | https://thetvdb.com/index.php?tab=series&id=360553 | Season 4 `Yatogame-chan Kansatsu Nikki Yonsatsume` tvdb map |
| https://anidb.net/anime/17012 | --- | Marked `Garden: Takamine-ke no Nirinka The Animation` as `hentai` |
| https://anidb.net/anime/17013 | --- | Marked `Kimi wa Yasashiku Netorareru The Animation` as `hentai` |
| https://anidb.net/anime/17015 | https://thetvdb.com/index.php?tab=series&id=412957 | Season 1 `Eiyuu Ou, Bu o Kiwameru Tame Tenseisu: Soshite, Sekai Saikyou no Minarai Kishi` tvdb map |
| https://anidb.net/anime/17053 | https://thetvdb.com/index.php?tab=series&id=355774 | Season 3 `Dr. Stone: New World` tvdb map |
| https://anidb.net/anime/17063 | https://thetvdb.com/index.php?tab=series&id=413542 | Season 1 `Ayakashi Triangle` tvdb map |
| https://anidb.net/anime/17064 | https://thetvdb.com/index.php?tab=series&id=393478 | Season 2 `Tokyo Revengers: Seiya Kessen Hen` tvdb map |
| https://anidb.net/anime/17075 | https://thetvdb.com/index.php?tab=series&id=422405 | Season 1 `Tsundere Akuyaku Reijou Liselotte to Jikkyou no Endou-kun to Kaisetsu no Kobayashi-san` tvdb map |
| https://anidb.net/anime/17077 | https://thetvdb.com/index.php?tab=series&id=404886 | Season 0 `Sasaki to Miyano: Koi ni Kizuku Mae no Chotto Shita Hanashi.` tvdb map |
| https://anidb.net/anime/17089 | https://thetvdb.com/index.php?tab=series&id=411329 | Season 2 `Kaginado (2022)` tvdb map |
| https://anidb.net/anime/17131 | https://thetvdb.com/index.php?tab=series&id=414562 | Season 1 `Kimi wa Houkago Insomnia` tvdb map |
| https://anidb.net/anime/17133 | --- | Marked `Inkou Kyoushi no Sai* Seikatsu Shidouroku` as `hentai` |
| https://anidb.net/anime/17140 | https://thetvdb.com/index.php?tab=series&id=414845 | Season 1 `Benriya Saitou-san, Isekai ni Iku` tvdb map |
| https://anidb.net/anime/17143 | https://thetvdb.com/index.php?tab=series&id=414908 | Season 1 `Ooyuki Umi no Kaina` tvdb map |
| https://anidb.net/anime/17146 | https://thetvdb.com/index.php?tab=series&id=414947 | Season 1 `Kami wa Game ni Uete Iru.` tvdb map |
| https://anidb.net/anime/17159 | https://thetvdb.com/index.php?tab=series&id=415378 | Season 1 `Saikyou Onmyouji no Isekai Tenseiki` tvdb map |
| https://anidb.net/anime/17183 | https://thetvdb.com/index.php?tab=series&id=388645 | Season 2 `Edens Zero (2023)` tvdb map |
| https://anidb.net/anime/17196 | https://thetvdb.com/index.php?tab=series&id=377543 | Season 2 `Jujutsu Kaisen (2023)` tvdb map |
| https://anidb.net/anime/17198 | https://thetvdb.com/index.php?tab=series&id=348545 | Season 4 `Kimetsu no Yaiba: Katanakaji no Sato Hen` tvdb map |
| https://anidb.net/anime/17203 | --- | Marked `Sazanami Souji ni Shojo o Sasagu: Saa, Jikkuri Medemashou ka` as `hentai` |
| https://anidb.net/anime/17212 | https://thetvdb.com/index.php?tab=series&id=344220 | Season 0 Episode 4 `Uma Musume: Pretty Derby (2022)` tvdb map |
| https://anidb.net/anime/17214 | https://thetvdb.com/index.php?tab=series&id=416998 | Season 1 `NieR:Automata Ver1.1a` tvdb map |
| https://anidb.net/anime/17240 | https://thetvdb.com/index.php?tab=series&id=320002 | Season 0 Episodes 7-8 `BanG Dream! Girls Band Party! 5th Anniversary Animation: Circle Thanks Party!` tvdb map |
| https://anidb.net/anime/17242 | --- | Marked `Isekai Yarisaa` as `hentai` |
| https://anidb.net/anime/17248 | https://thetvdb.com/index.php?tab=series&id=417675 | Season 1 `Isekai One Turn Kill Nee-san: Ane Douhan no Isekai Seikatsu Hajimemashita` tvdb map |
| https://anidb.net/anime/17256 | https://thetvdb.com/index.php?tab=series&id=415821 | Season 1 `Spy Kyoushitsu` tvdb map |
| https://anidb.net/anime/17259 | --- | Marked `Kyonyuu Onna Senshi Dogeza Saimin` as `hentai` |
| https://anidb.net/anime/17260 | https://thetvdb.com/index.php?tab=series&id=418185 | Season 1 `Inu ni Nattara Suki na Hito ni Hirowareta.` tvdb map |
| https://anidb.net/anime/17262 | https://thetvdb.com/index.php?tab=series&id=423563 | Season 1 `Eternal Boys` tvdb map |
| https://anidb.net/anime/17263 | https://thetvdb.com/index.php?tab=series&id=417983 | Season 1 `Ragna Crimson` tvdb map |
| https://anidb.net/anime/17271 | https://thetvdb.com/index.php?tab=series&id=406152 | Season 2 `Hanma Baki: Son of Ogre 2` tvdb map |
| https://anidb.net/anime/17273 | https://thetvdb.com/index.php?tab=series&id=418123 | Season 1 `Dead Dead Demon's Dededededestruction` tvdb map |
| https://anidb.net/anime/17285 | https://thetvdb.com/index.php?tab=series&id=418376 | Season 1 `4-nin wa Sorezore Uso o Tsuku` tvdb map |
| https://anidb.net/anime/17288 | https://thetvdb.com/index.php?tab=series&id=418340 | Season 1 `Lv1 Maou to One Room Yuusha` tvdb map |
| https://anidb.net/anime/17290 | https://thetvdb.com/index.php?tab=series&id=418367 | Season 1 `Isekai Nonbiri Nouka` tvdb map |
| https://anidb.net/anime/17291 | --- | Marked `Tsugunai` as `hentai` |
| https://anidb.net/anime/17294 | https://thetvdb.com/index.php?tab=series&id=318860 | Season 2 `Masamune-kun no Revenge R` tvdb map |
| https://anidb.net/anime/17295 | https://thetvdb.com/index.php?tab=series&id=402636 | Season 2 `Shin Shinka no Mi: Shiranai Uchi ni Kachigumi Jinsei` tvdb map |
| https://anidb.net/anime/17297 | --- | Marked `#Ima Made de Ichiban Yokatta Sex The Animation` as `hentai` |
| https://anidb.net/anime/17660 | --- | Marked `Mama Katsu: Midareru Mama-tachi no Himitsu` as `hentai` |
| https://anidb.net/anime/17661 | --- | Marked `Roshutsu-kei Mahou Joshidaisei Christhea` as `hentai` |
| https://anidb.net/anime/17664 | https://thetvdb.com/index.php?tab=series&id=262954 | Season 5 Episodes 25-38 `JoJo no Kimyou na Bouken: Stone Ocean (Part 3)` tvdb map |

### CODE REVIEW

**Comment by plantysnake** [comment]
@Brutuz I have some conserns about this ones

https://anidb.net/anime/16543 and https://anidb.net/anime/16999

They are clearly a H, but they did have a censured run and there IS a tvdb page for both seasons
https://thetvdb.com/index.php?tab=series&id=424562

Should they be mapped?

**Comment by plantysnake** [comment]
Actually, same goes for `Overflow`
https://anidb.net/anime/15274
https://thetvdb.com/index.php?tab=series&id=373728

**Comment by plantysnake** [comment]
And same for `Joshi Ochi! 2-kai kara Onnanoko ga... Futte Kita!?`
But it does have mapping in list
https://anidb.net/anime/14112
https://thetvdb.com/index.php?tab=series&id=349640

Then do I need to remap those?

**Comment by BrutuZ** [comment]
If there's a matching TVDB entry, it should be mapped rather than not, even these AnimeFiesta H that have clean/shorter versions. The data applies to both and the user will know which version they have 😏

I see that tag on `tvdbid` not as much for classification, but mostly for the entries to be removed from `anime-lists-todo.xml` by the list generation scripts.

**Comment by plantysnake** [comment]
> If there's a matching TVDB entry, it should be mapped rather than not, even these AnimeFiesta H that have clean/shorter versions. The data applies to both and the user will know which version they have 😏
> 
> I see that tag on `tvdbid` not as much for classification, but mostly for the entries to be removed from `anime-lists-todo.xml` by the list generation scripts.

Gotcha! I'll re-map them.

**Comment by plantysnake** [comment]
Same probably applies for `Sazanami Souji ni Shojo o Sasagu: Saa, Jikkuri Medemashou ka`
- https://anidb.net/anime/17203
- https://thetvdb.com/index.php?tab=series&id=424563
But the tvdb page is still pending moderation, so as for now, it probably should be just `hentai`

**Comment by plantysnake** [comment]
@BrutuZ one more tricky situation
There is a tvdb page for `Tokyo Daigaku Monogatari`, but from 2 ep, there only 1 is present
- https://anidb.net/anime/2788
- https://thetvdb.com/index.php?tab=series&id=395530

**Comment by BrutuZ** [comment]
> @BrutuZ one more tricky situation There is a tvdb page for `Tokyo Daigaku Monogatari`, but from 2 ep, there only 1 is present
> 
>     * https://anidb.net/anime/2788
> 
>     * https://thetvdb.com/index.php?tab=series&id=395530
> 
> 
> I'll map it as is, but if you have any suggestions, I'd like to listen.

Add the missing episode to the TVDB entry :)

**Comment by BrutuZ** [comment]
> Same probably applies for `Sazanami Souji ni Shojo o Sasagu: Saa, Jikkuri Medemashou ka`
>     * https://anidb.net/anime/17203
>     * https://thetvdb.com/index.php?tab=series&id=424563
> 
> But the tvdb page is still pending moderation, so as for now, it probably should be just `hentai`
> Same situation with `Rape Gouhouka!!!`
>     * https://anidb.net/anime/14399
>     * https://thetvdb.com/index.php?tab=series&id=424469

For the pending ones use your own discretion.

**IMHO** the value of those TVDB entries is debatable at the moment. To me the point is to have a source of metadata, if the TVDB entry is empty and offers no information there's little to be gained from it other than the hope it is approved and someone fills the information eventually like I did with the previous one

**Comment by plantysnake** [comment]
> For the pending ones use your own discretion.
All right, I'll probably check in couple of month for these entries and if approved and have some information, I'll map them. But as for now, let's just mark them `hentai` and that's it.

**Comment by plantysnake** [comment]
It seems, this PR got really huge, so I'll stop adding new ones to this one. Sorry, I got carried away.

**Comment by BrutuZ** [comment]
Those are mostly additions, only changes are to replace the `hentai` tag with a TVDB ID and there are no mapping-lists, I'll trust you on this and merge without double-checking them all 😅
Only potential issues I foresee are wrong IDs, still easier to spot and fix than no ID at all I guess.

**Pull request merged**
