### PR TITLE
Updates for 17885 to 17917

### PR DESCRIPTION
**Pull request by Middlepepper**
Updates for 17885 to 17917, 

Change Log
- Flagged Entries based on Type (i.e web, music video etc)
- Added TVBD, TMDB and IMDB as per list below.
- Flagged with Unknown if no entry on TVDB

| AniDB | TVDB/TMDB/IMDB | Notes |
|-------|----------------|-------|
| https://anidb.net/anime/17885 | https://thetvdb.com/index.php?tab=series&id=429213 | Yao-Chinese Folktales |
| https://anidb.net/anime/17887 | https://thetvdb.com/index.php?tab=series&id=431804 | Kawagoe Boys Sing |
| https://anidb.net/anime/17890 | https://www.themoviedb.org/movie/1094621 | Eiga Precure All Stars F |
| https://anidb.net/anime/17891 | https://thetvdb.com/index.php?tab=series&id=431891 | Sore Shikanai Wakenai Deshou |
| https://anidb.net/anime/17896 | https://thetvdb.com/index.php?tab=series&id=321285 | Boruto: Naruto Next Generations (Dai Ni Bu) |
| https://anidb.net/anime/17904 | https://thetvdb.com/index.php?tab=series&id=375271 | Fumetsu no Anata e Season 3 |
| https://anidb.net/anime/17905 | https://www.themoviedb.org/movie/1106916 | Kaitou Queen no Yuuga na Vacances |
| https://anidb.net/anime/17906 | https://thetvdb.com/index.php?tab=series&id=432050 | Kimi no Koto ga Dai Dai Dai Dai Daisuki na 100 Nin no Kanojo |
| https://anidb.net/anime/17907 | https://thetvdb.com/index.php?tab=series&id=432720 | Kibou no Chikara: Otona Precure '23 |
| https://anidb.net/anime/17908 | https://thetvdb.com/index.php?tab=series&id=304476 | Mahou Tsukai Precure! 2 |
| https://anidb.net/anime/17909 | https://thetvdb.com/index.php?tab=series&id=432455 | Nige Jouzu no Wakagimi |
| https://anidb.net/anime/17910 | https://thetvdb.com/index.php?tab=series&id=432449 | Mahou Shoujo ni Akogarete |
| https://anidb.net/anime/17911 | https://thetvdb.com/index.php?tab=series&id=432476 | Tsuma, Shougakusei ni Naru. |
| https://anidb.net/anime/17913 | https://thetvdb.com/index.php?tab=series&id=432505 | Kinnikuman (Shin Series) |
| https://anidb.net/anime/17914 | https://thetvdb.com/index.php?tab=series&id=432531 | Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san |
| https://anidb.net/anime/17915 | https://thetvdb.com/index.php?tab=series&id=427239 | Dead Mount Death Play (2023) |

### CODE REVIEW

**Comment by BrutuZ** [comment]
What is the reason to add just `tvdbid=unknown` to an entry?
That's just moving them from [anime-list-todo.xml](https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-todo.xml) to [anime-list-unknown.xml](https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-unknown.xml)

Existing ones are legacy AFAIK. Or a few entries that had a tvdbid but it got deleted (likely TVDB changed it but wasn't updated on the list)

**Comment by Middlepepper** [comment]
So my logic was that the "unknown" tag was for anything that doesn't have an active entry in TVDB. i.e it will need to be manually added to the TVDB.

So I've check every entry on TVDB in my pulls and any that cannot be mapped as there no TVDB I've marked as unknown so that there in the Unknown list to go through when there time to make each entry on the TVDB.

From the readme I was looking at this part as guidance.
```
tvdbid - theTVDB.com series id (do not use movie IDs). Multi-episode titles not found on theTVDB.com are marked as "unknown", as they may eventually get added and this makes it easier to re-check (via anime-list-unknown.xml). 
One-off titles that won't ever be added to theTVDB.com (movies, TV specials, one-shot OVAs) are marked by their AniDb.net type, unless they can be associated to a multi-episode series (in which case they use the corresponding theTVDB.com id or "unknown").
```

**Comment by BrutuZ** [comment]
Seems unnecessarily complicated to have 2 files tracking unidentified entries IMO.

I mean, if that's the logic it would make more sense for the update-list script to make unknown be the default value for new entries rather than empty.

**Comment by Middlepepper** [comment]
Yeah It is a bit odd, but I'm doing a lot of update so I don't want to make it worthless by deviating from the readme until we have a firm decision on the way forward. I don't think anyone else in the Org? (https://github.com/Anime-Lists) chimed in either.

**Pull request closed without merging**
