### PR TITLE
fix-defaulttvdbseason="a"

### PR DESCRIPTION
**Pull request by Arial-Z**
Fix some animes with `defaulttvdbseason="1"` despiste spanning on multiple tvdb seasons
| AniDB | TVDB | Notes |
| --- | --- | --- |
| https://anidb.net/anime/590 | https://thetvdb.com/index.php?tab=series&id=72491 | TVDB S1 to S4 |
| https://anidb.net/anime/3468 | https://thetvdb.com/index.php?tab=series&id=79895 | TVDB S1 to S4 |
| https://anidb.net/anime/8865 | https://thetvdb.com/index.php?tab=series&id=256705 | TVDB S1 to S2 |

### CODE REVIEW

**Comment by Guslletas** [comment]
So I just saw this, why do shows spanning on multiple tvdb seasons have to use absolute mappings despite working perfectly with the regular mapping? When you have regular mappings you know the show is perfectly matched but if you have absolute mappings mapping each season is optional, forcing you to access tvdb to check the seasons. I use these mappings on my own app and since I don't want to use tvdb api I have to manually overwrite the shows with absolute mappings with my own mappings. I propose either making every show with absolute mappings have every season mapped or switching every finished absolutely mapped show to regular mappings(since we know how each season maps and there won't be any more changes) and only leaving the ongoing ones with absolute mappings with optional season mappings.

**Comment by Arial-Z** [comment]
It did not work correctly the whole anidb show was linked only to the first tvdb season, and not S1 to S2 or even S1 to S4, i will add the missing mapping for Slam Dunk and Gintama S1, Uchuu Kyoudai already have a complete season mapping

**Comment by Guslletas** [comment]
The first two needed mappings but Uchuu Kyoudai didn't need any change, all its seasons were perfectly mapped using the regular mapping and there was no need to switch it to absolute mapping

**Comment by Arial-Z** [comment]
Using `a` for multiple seasons seems more logic than using `1` for S1 and also multiples seasons.
`a` is already used in the liste and follow the guidelines

**Comment by Guslletas** [comment]
`a` is used for absolute mappings and that's it, nothing says it must be used to map multiple seasons, in fact it's even worse because you lose information with it. When using `a` it means a season might or might not be mapped(look at One Piece or Bleach), mapping seasons is optional because the mapping is using absolute numbers and you are supposed to check to which season an episode belongs to by accesing tvdb(whose api is supposed to require a paid subscription in the future so if you ever want to use this once it goes paid any show using absolute mappings will require you to pay the sub to access tvdb api in your app). If  you use regular mappings it means all the seasons are there, so you don't have to check tvdb and there already a lot of shows using regular mappings for multiple seasons(just search in the file the string `anidbseason="1" tvdbseason="2" start` and check how many of those use `a`), in fact I'd say the one you changed is an outlier because most shows using `a` don't have season mappings(there are some exceptions like Inuyasha) and most shows that have seasons mapped are using the regular mappings. As I said before, the best course is either making mandatory having all shows using `a` have all seasons mapped or have all shows with mapped seasons using regular mappings. My pick would be leaving `a` only for currently airing shows(even if it's decided to force `a` to have the seasons mapped) and the regular ones for already finished shows, this way we can we get new info without changing the list structure(we can know whether if a show is airing or not) and for shows using `a` we leave the choice to the user to either trust the season mappings they have(if they have them) or check tvdb(to get the mappings and/or verify the current ones since they might not be up to date because it's a currently airing show)

**Comment by Arial-Z** [comment]
Your search return 29 results about 1/3 of them use `a`, on the other hand 73 entry use `a` and some don't even have a mapping, it's clearly a mixed usage, i don't really know what to tell you, you're asking for change in the guideline is some random PR, create a issue ticket and see what creator, maintainer and people think about it.

**Comment by Guslletas** [comment]
I'm not asking for a change in any guideline, the guideline doesn't force you to use `a` only gives you the choice. I'm asking you not to switch to `a` mappings that already work and follow the guideline like the Uchuu Kyoudai one

**Comment by BrutuZ** [comment]
Going on a tangent here...
>When using a it means a season might or might not be mapped(look at One Piece or Bleach)

What's that about Bleach not being mapped? It split just fine for me with HAMA, same for Fairy Tail.
> api is supposed to require a paid subscription in the future so if you ever want to use this once it goes paid any show using absolute mappings will require you to pay the sub to access tvdb api in your app

If TheTVDB API gets paywalled as they promised (but thankfully keep postponing), then the list will become mostly useless anyways.
> (we can know whether if a show is airing or not)

Not really the point here

Really hard to read all that without any paragraphs BTW

**Comment by Guslletas** [comment]
>What's that about Bleach not being mapped? It split just fine for me with HAMA, same for Fairy Tail.  

Because `a` means it's mapping using the absolute episode number, aka anidb episode number + offset = tvdb absolute number, how do you know which season that tvdb absolute number episode belongs to? You either check tvdb api, have it on some list you have built or maybe plex accepts tvdb absolute episode numbers(not sure).  

>If TheTVDB API gets paywalled as they promised (but thankfully keep postponing), then the list will become mostly useless anyways.  

I'm using it and I'm not using any tvdb info either from their api or some external file other than this list, this is why regular mappings are way better. If you know how many episodes an anidb show has(which you can get from anidb api or some lists like https://github.com/manami-project/anime-offline-database) and have regular mappings you can get the tvdb show structure(aka seasons+episodes), having absolute mappings requires you to check in tvdb the season and episode number. 

>Not really the point here  

Yeah I was pointing out a possible advantage of doing it the way I mentioned that also didn't require changing the list structure so it wouldn't require any code changes and would be transparent for everyone. 

>Really hard to read all that without any paragraphs BTW  

Yeah, my bad, sorry.

**Pull request merged**
